#!/usr/bin/env bash

alias unittest='RUN_MODE=unittest python -m unittest' 
alias unittest_coverage='RUN_MODE=unittest coverage run -m unittest discover'
export SG_PROJECTS_DIR="${HOME}/projects"
export VAGRANT_HOSTNAME="vagrant-fullstack-centos7"
export VAGRANT_EMAIL_ADDRESS="lmeigs+vagrant@shiftgig.com"
export VAGRANT_REFRESH_DATABASES=0
export VAGRANT_SKIP_ANSIBLE=1
