return {
    { "nvim-mini/mini.pairs", enabled = false },
    { "nvim-mini/mini.ai", enabled = false },
    { "catppuccin/nvim", enabled = false },
    { "MagicDuck/grug-far.nvim", enabled = false },
    { "folke/flash.nvim", enabled = false },
    { "folke/trouble.nvim", enabled = false },
    { "folke/todo-comments.nvim", enabled = false },
    { "folke/noice.nvim", enabled = false },

    -- { "neovim/nvim-lspconfig", enabled = false },
    -- { "mason-org/mason-lspconfig.nvim", enabled = false },
    -- { "mason-org/mason.nvim", enabled = false },
    -- { "mfussenegger/nvim-lint", enabled = false },
    -- { "folke/ts-comments.nvim", enabled = false },
    -- { "folke/lazydev.nvim", enabled = false },
    -- { "folke/which-key.nvim", enabled = false },
    -- { "lewis6991/gitsigns.nvim", enabled = false },
    -- { "stevearc/conform.nvim", enabled = false },
    -- { "nvim-treesitter/nvim-treesitter", enabled = false },
    -- { "akinsho/bufferline.nvim", enabled = false },
    -- { "nvim-lualine/lualine.nvim", enabled = false },
    -- { "nvim-mini/mini.icons", enabled = false },
    -- { "MunifTanjim/nui.nvim", enabled = false },
    -- --{ "snacks.nvim", enabled = false },
    -- { "folke/persistence.nvim", enabled = false },
    -- { "nvim-lua/plenary.nvim", enabled = false },
}
